
const ADMIN_EMAILS=["masjidalkhoirgandu@gmail.com","rizkiku255@gmail.com"];
const QUOTES=[
["Sesungguhnya shalat itu mencegah dari perbuatan keji dan mungkar.","QS. Al-'Ankabut: 45"],
["Dan barang siapa bertakwa kepada Allah, niscaya Dia menjadikan baginya jalan keluar.","QS. At-Talaq: 2"],
["Maka ingatlah Aku, niscaya Aku akan mengingatmu.","QS. Al-Baqarah: 152"],
["Sesungguhnya bersama kesulitan ada kemudahan.","QS. Al-Insyirah: 6"],
["Sebaik-baik manusia adalah yang paling bermanfaat bagi manusia lainnya.","HR. Ahmad"],
["Amal yang paling dicintai Allah adalah yang paling konsisten walaupun sedikit.","HR. Bukhari dan Muslim"],
["Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.","QS. Al-Baqarah: 286"],
["Barang siapa menempuh jalan untuk mencari ilmu, Allah mudahkan baginya jalan menuju surga.","HR. Muslim"],
["Dan barang siapa bersyukur, maka sesungguhnya dia bersyukur untuk kebaikan dirinya sendiri.","QS. Luqman: 12"],
["Bersegeralah menuju ampunan dari Tuhanmu dan surga yang luasnya seluas langit dan bumi.","QS. Ali 'Imran: 133"],
["Perumpamaan orang yang menginfakkan hartanya di jalan Allah seperti sebutir benih yang menumbuhkan tujuh bulir.","QS. Al-Baqarah: 261"],
["Janganlah kamu berputus asa dari rahmat Allah.","QS. Az-Zumar: 53"]
];
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function initNav(){const b=document.querySelector(".hamb"),l=document.querySelector(".links");if(b)b.onclick=()=>l.classList.toggle("open");const p=location.pathname.split("/").pop()||"index.html";document.querySelectorAll(".links a[data-page]").forEach(a=>{if(a.dataset.page===p)a.classList.add("active")})}
function initDate(){const d=new Date(),f=new Intl.DateTimeFormat("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"});document.querySelectorAll("[data-today]").forEach(x=>x.textContent=f.format(d));const key=Math.floor(new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()/86400000),q=QUOTES[((key%QUOTES.length)+QUOTES.length)%QUOTES.length];const qt=document.querySelector("#quoteText"),qs=document.querySelector("#quoteSource");if(qt)qt.textContent=q[0];if(qs)qs.textContent=q[1];document.querySelectorAll("[data-year]").forEach(x=>x.textContent=d.getFullYear())}
function clock(){const x=document.querySelector("#liveClock");if(x)x.textContent=new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date())+" WIB"}
async function prayer(){const box=document.querySelector("#prayers");if(!box)return;try{const r=await fetch("https://api.aladhan.com/v1/timingsByAddress?address=Jetak, Klitik, Geneng, Ngawi, Jawa Timur, Indonesia&method=20");const j=await r.json();if(j.code!==200)throw Error();const t=j.data.timings;const names=[["Subuh","Fajr"],["Dzuhur","Dhuhr"],["Ashar","Asr"],["Maghrib","Maghrib"],["Isya","Isha"],["Imsak","Imsak"]];box.innerHTML=names.map(([n,k])=>`<div class="pray" data-time="${t[k]||""}"><small>${n}</small><strong>${(t[k]||"--:--").slice(0,5)}</strong></div>`).join("");const now=new Date(),cur=now.getHours()*60+now.getMinutes();let idx=-1;[...box.children].forEach((c,i)=>{const [h,m]=(c.dataset.time||"00:00").split(":").map(Number);if(idx<0&&h*60+m>cur)idx=i});if(idx<0)idx=0;if(box.children[idx])box.children[idx].classList.add("next");const d=new Date(j.data.date.timestamp*1000);const pd=document.querySelector("#prayerDate");if(pd)pd.textContent=new Intl.DateTimeFormat("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(d)}catch(e){box.innerHTML='<div class="empty" style="grid-column:1/-1">Jadwal shalat sedang tidak tersedia. Silakan muat ulang beberapa saat lagi.</div>'}}
function initAI(){const form=document.querySelector("#aiForm"),input=document.querySelector("#aiInput"),msgs=document.querySelector("#aiMsgs");if(!form)return;document.querySelectorAll("[data-question]").forEach(b=>b.onclick=()=>{input.value=b.dataset.question;input.focus()});form.onsubmit=async e=>{e.preventDefault();const q=input.value.trim();if(!q)return;msgs.innerHTML+=`<div class="msg user">${esc(q)}</div>`;input.value="";msgs.scrollTop=msgs.scrollHeight;const wait=document.createElement("div");wait.className="msg bot";wait.textContent="Sedang mencari jawaban…";msgs.appendChild(wait);try{const r=await fetch("/.netlify/functions/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q})});const j=await r.json();wait.textContent=j.answer||"Maaf, saya belum dapat menjawab sekarang."}catch(err){wait.textContent="Fitur AI belum tersambung. Admin perlu mengisi OPENAI_API_KEY di Netlify. Informasi masjid tetap dapat dibaca dari menu website."}msgs.scrollTop=msgs.scrollHeight}}
function init(){initNav();initDate();clock();setInterval(clock,1000);prayer();initAI()}document.addEventListener("DOMContentLoaded",init);
